export const types = {
    ASYNC_LOGGING_IN:  'ASYNC_LOGGING_IN',
    LOGGING:           'LOGGING',
    LOGIN_SUCCEEDED:   'LOGIN_SUCCEEDED',
    LOGIN_FAILED:      'LOGIN_FAILED',

    ASYNC_LOGGING_OUT: 'ASYNC_LOGGING_OUT',
    LOGOUT_SUCCEEDED:  'LOGOUT_SUCCEEDED',
    LOGOUT_FAILED:     'LOGOUT_FAILED',

    ASYNC_SIGNING:     'ASYNC_SIGNING',
    SIGNIN_SUCCEEDED:  'SIGNIN_SUCCEEDED',
    SIGNIN_FAILED:     'SIGNIN_FAILED',
}